/*********************************************************************************************
@Created By :      Amit Rajan
@CreatedDate :     4 July 2016
Description :      Constants class for Community Context creation
****************************************************************************************************/
public class CommunityConstantsUtility{

    //Context sub types
    public static final String ENTITLEMENT_DEVELOPMENT     = 'Development Project';
    public static final String ENTITLEMENT_SUPPORT         = 'Support for FAEs';
    public static final String ENTITLEMENT_CONTRACT        = 'NXP Support Contract';
    public static final String ENTITLEMENT_NONTECHNICAL    = 'Non-Technical';
    
    
    
    //Context Entitlement type
    public static final String ENTITLEMENT_FREETYPE        = 'Free';
    
    public static final String PARTICIPANT                 = 'Participant';
    public static final String OBSERVER                    = 'Observer';
    
    
    //Entitlement Contact Owner 
    public static final String ENTITLEMENTCONTACT_OWNER    = 'Owner';
    public static final String ENTITLEMENTCONTACT_SILENT   = 'Silent Observer';
    
    //Entitlement Contact Rejected Status
    public static final String REJECTED_STATUS             = 'Rejected';
    public static final String ACCEPTED_STATUS             = 'Accepted';
    public static final String PENDING_STATUS              = 'Pending';
    
    
    //Dummy Other Entitlement Id
    public static final ID DUMMY_ENTITLEMENTID             = '5504E0000001k3O';
    public static final String ENTITLEMENT_OTHERSNAME      = 'Non-categorized cases';
    
    
    
    
}