/*********************************************************************************************
@Created By :      Amrutha R
@CreatedDate :     23 Mar 2015
Description :      Class to schedule accountContactMappingBatch class
***************************************************************************************************/

global class scheduleAccountContactMappingBatch implements Schedulable
{
   global void execute(SchedulableContext sc) 
   {/*
      accountContactMappingBatch b = new accountContactMappingBatch(); 
      database.executebatch(b);*/
   }
}